FROM centos

COPY conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN yum install -y  nginx && yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
    yum install -y \
        php71u-fpm \
	php71u-common\
	php71u-cli \
	unzip --enablerepo=ius && yum clean all

RUN mkdir /nginx

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY test.php /nginx

ADD https://github.com/BlackrockDigital/startbootstrap-agency/archive/master.zip ./master.zip
RUN unzip master.zip && mv startbootstrap-agency-master/* /nginx

COPY conf/start.sh /start.sh
RUN chmod +x /start.sh

CMD /start.sh


